# Project: ProductStore2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Product.o ProductManager.o
LINKOBJ  = main.o Product.o ProductManager.o
LIBS     = -L"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/lib" -L"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/include" -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/include" -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/DOWNLOADS_C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ProductStore2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Product.o: Product.cpp
	$(CPP) -c Product.cpp -o Product.o $(CXXFLAGS)

ProductManager.o: ProductManager.cpp
	$(CPP) -c ProductManager.cpp -o ProductManager.o $(CXXFLAGS)
